# fly.toml file generated for albion-market-discord-bot on 2023-04-03T14:46:51+09:00

app = "albion-market-discord-bot"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "sin"

[build]
  builtin = "node"

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  protocol = "tcp"
  script_checks = []
  tcp_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
